/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as StyleQuizRouteImport } from './routes/style-quiz'
import { Route as SizingRouteImport } from './routes/sizing'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as OrderHistoryRouteImport } from './routes/order-history'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiStylistRouteImport } from './routes/ai-stylist'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ApiTryOnRouteImport } from './routes/api/try-on'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminAiRouteImport } from './routes/admin.ai'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleQuizRoute = StyleQuizRouteImport.update({
  id: '/style-quiz',
  path: '/style-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SizingRoute = SizingRouteImport.update({
  id: '/sizing',
  path: '/sizing',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderHistoryRoute = OrderHistoryRouteImport.update({
  id: '/order-history',
  path: '/order-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStylistRoute = AiStylistRouteImport.update({
  id: '/ai-stylist',
  path: '/ai-stylist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryOnRoute = ApiTryOnRouteImport.update({
  id: '/api/try-on',
  path: '/api/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-stylist': typeof AiStylistRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/my-orders': typeof MyOrdersRoute
  '/order-history': typeof OrderHistoryRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRoute
  '/sizing': typeof SizingRoute
  '/style-quiz': typeof StyleQuizRoute
  '/track-order': typeof TrackOrderRoute
  '/try-on': typeof TryOnRoute
  '/wishlist': typeof WishlistRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/order/$id': typeof OrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-stylist': typeof AiStylistRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/my-orders': typeof MyOrdersRoute
  '/order-history': typeof OrderHistoryRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRoute
  '/sizing': typeof SizingRoute
  '/style-quiz': typeof StyleQuizRoute
  '/track-order': typeof TrackOrderRoute
  '/try-on': typeof TryOnRoute
  '/wishlist': typeof WishlistRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/order/$id': typeof OrderIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-stylist': typeof AiStylistRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/my-orders': typeof MyOrdersRoute
  '/order-history': typeof OrderHistoryRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRoute
  '/sizing': typeof SizingRoute
  '/style-quiz': typeof StyleQuizRoute
  '/track-order': typeof TrackOrderRoute
  '/try-on': typeof TryOnRoute
  '/wishlist': typeof WishlistRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/order/$id': typeof OrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-stylist'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/lookbook'
    | '/my-orders'
    | '/order-history'
    | '/returns'
    | '/shop'
    | '/sizing'
    | '/style-quiz'
    | '/track-order'
    | '/try-on'
    | '/wishlist'
    | '/admin/ai'
    | '/admin/catalog'
    | '/admin/customers'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/try-on'
    | '/order/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-stylist'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/lookbook'
    | '/my-orders'
    | '/order-history'
    | '/returns'
    | '/shop'
    | '/sizing'
    | '/style-quiz'
    | '/track-order'
    | '/try-on'
    | '/wishlist'
    | '/admin/ai'
    | '/admin/catalog'
    | '/admin/customers'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/try-on'
    | '/order/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-stylist'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/lookbook'
    | '/my-orders'
    | '/order-history'
    | '/returns'
    | '/shop'
    | '/sizing'
    | '/style-quiz'
    | '/track-order'
    | '/try-on'
    | '/wishlist'
    | '/admin/ai'
    | '/admin/catalog'
    | '/admin/customers'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/try-on'
    | '/order/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiStylistRoute: typeof AiStylistRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LookbookRoute: typeof LookbookRoute
  MyOrdersRoute: typeof MyOrdersRoute
  OrderHistoryRoute: typeof OrderHistoryRoute
  ReturnsRoute: typeof ReturnsRoute
  ShopRoute: typeof ShopRoute
  SizingRoute: typeof SizingRoute
  StyleQuizRoute: typeof StyleQuizRoute
  TrackOrderRoute: typeof TrackOrderRoute
  TryOnRoute: typeof TryOnRoute
  WishlistRoute: typeof WishlistRoute
  ApiTryOnRoute: typeof ApiTryOnRoute
  OrderIdRoute: typeof OrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-quiz': {
      id: '/style-quiz'
      path: '/style-quiz'
      fullPath: '/style-quiz'
      preLoaderRoute: typeof StyleQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sizing': {
      id: '/sizing'
      path: '/sizing'
      fullPath: '/sizing'
      preLoaderRoute: typeof SizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-history': {
      id: '/order-history'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof OrderHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-stylist': {
      id: '/ai-stylist'
      path: '/ai-stylist'
      fullPath: '/ai-stylist'
      preLoaderRoute: typeof AiStylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/try-on': {
      id: '/api/try-on'
      path: '/api/try-on'
      fullPath: '/api/try-on'
      preLoaderRoute: typeof ApiTryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiStylistRoute: AiStylistRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LookbookRoute: LookbookRoute,
  MyOrdersRoute: MyOrdersRoute,
  OrderHistoryRoute: OrderHistoryRoute,
  ReturnsRoute: ReturnsRoute,
  ShopRoute: ShopRoute,
  SizingRoute: SizingRoute,
  StyleQuizRoute: StyleQuizRoute,
  TrackOrderRoute: TrackOrderRoute,
  TryOnRoute: TryOnRoute,
  WishlistRoute: WishlistRoute,
  ApiTryOnRoute: ApiTryOnRoute,
  OrderIdRoute: OrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
